from pathlib import Path

path = Path("STATUS.md")
text = path.read_text()

def replace_once(old, new):
    global text
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"Expected exactly one occurrence, found {count}: {old[:120]}")
    text = text.replace(old, new, 1)

replace_once(
    "FACTORY_PHASE=ART_PR10_EMF_CEM_MERGED_POSTMERGE_ACTIONS_GREEN_AUDITED_SOURCE_BUILD_PASS_TARGET_EXACT_RUNTIME_UNPROVEN_MAIN_SONAR_ANALYSIS_CANCELLED_STATUS_CLOSEOUT",
    "FACTORY_PHASE=ART_PR11_ANIMATED_JAVA_MERGED_POSTMERGE_ACTIONS_GREEN_TARGET_EXACT_DATAPACK_DISPLAY_ENTITY_GAMETEST_PASS_REAL_PLUGIN_EXPORT_UNPROVEN_MAIN_SONAR_ANALYSIS_CANCELLED_STATUS_CLOSEOUT",
)
replace_once("CURRENT_BRANCH=docs/art-pr10-closeout-status", "CURRENT_BRANCH=docs/art-pr11-closeout-status")
replace_once(
    "CURRENT_MAIN_BEFORE_STATUS_UPDATE=d1cc1e144c48d9071a61a67c3f09b569ec4e1354",
    "CURRENT_MAIN_BEFORE_STATUS_UPDATE=a4d9a715f8e9213d458df625336c1ef8a096fbf9",
)
replace_once(
    "HEAD_AT_LAST_GREEN_VERIFICATION=d1cc1e144c48d9071a61a67c3f09b569ec4e1354",
    "HEAD_AT_LAST_GREEN_VERIFICATION=a4d9a715f8e9213d458df625336c1ef8a096fbf9",
)
replace_once(
    "OPEN_PRS_AT_STATUS_WRITE=PR53_MERGED; PR10_STATUS_CLOSEOUT_PR_PENDING; NO_OTHER_OPEN_PRS",
    "OPEN_PRS_AT_STATUS_WRITE=PR59_MERGED; PR60_CONSTRUCTION_C7_OPEN_NON_OVERLAPPING; PR11_STATUS_CLOSEOUT_PR_PENDING",
)

anchor = "PR10_STATE=MERGED_POSTMERGE_ACTIONS_GREEN_PREMERGE_SONAR_GREEN_UPSTREAM_SOURCE_BUILD_PASS_TARGET_EXACT_RUNTIME_UNPROVEN; GLOBAL_MAIN_SONAR_NOT_PASS"
pr11 = """PR11_PLAN_TARGET=ANIMATED_JAVA; TARGET=MINECRAFT_1.21.1_NEOFORGE_21.1.248_JAVA_21
PR11_ANIMATED_JAVA_PR=59
PR11_ANIMATED_JAVA_FINAL_HEAD=e43b1d6d777f1785bd0d82392903ace91387b020
PR11_ANIMATED_JAVA_MERGE_COMMIT=a4d9a715f8e9213d458df625336c1ef8a096fbf9
PR11_PLUGIN_AUTHORITY=Animated-Java/animated-java@a5fc548d2a53cc0887fa070db33ccfcef1cd3541; VERSION=1.10.2; RELEASE_ASSET=animated_java.js; RELEASE_ASSET_SHA256=81aadc4def796d97dab6642ad05b564b470ecadcaf455c8cc5826c9e24759672
PR11_BLOCKBENCH_AUTHORITY=JannisX11/blockbench@794e964e966b6783b4e9b98ecbdda5152c0620cc; VERSION=5.1.6; MIN_BLOCKBENCH=5.1.4; VARIANT=DESKTOP
PR11_BLUEPRINT_SOURCE_POLICY=AJBLUEPRINT_SOURCE_PRESERVED; FORMAT=animated-java:format/blueprint; CODEC=animated_java:codec/blueprint; NO_SILENT_PROVIDER_CONVERSION
PR11_PLUGIN_MODE_POLICY=UNAUDITED_FAIL_CLOSED; DATAPACK_RESOURCE_PACK_PIPELINE_ONLY
PR11_FEATURE_AWARENESS=VARIANTS; LOCATORS; CAMERAS; FUNCTION_KEYFRAMES; VARIANT_KEYFRAMES; NON_MUTATING_INSPECTION
PR11_TDD_RED1_RUN=34636813094; 1_OF_5_PASS; 4_EXPECTED_MISSING_API_FAIL
PR11_TDD_RED2_RUN=34638219510; 3_OF_6_PASS; 3_EXPECTED_CONTRACT_FAIL; EXISTING_REGRESSIONS_GREEN
PR11_PREMERGE_FINAL_RUN=34639556469; SUCCESS
PR11_PR_RUN=34644183605; SUCCESS
PR11_PREMERGE_SONAR=CHECK_103411724378; QUALITY_GATE_PASS; 0_NEW_ISSUES; 0_ACCEPTED_ISSUES; 0_SECURITY_HOTSPOTS; 0.0_PERCENT_DUPLICATION_ON_NEW_CODE
PR11_RUNTIME_SMOKE_RUN=34638984175; JOB=103393743390; TARGET_EXACT_MINECRAFT_1_21_1_NEOFORGE_21_1_248_JAVA_21; 1_OF_1_REQUIRED_GAMETEST_PASS; FUNCTION=factorypr11:smoke/summon
PR11_POSTMERGE_RUN=34644802268; SUCCESS
PR11_POSTMERGE_ACTIONS=24_OF_24_WORKFLOWS_SUCCESS
PR11_POSTMERGE_SONAR=CHECK_103413605981; ANALYSIS_FAILED; CONCLUSION_CANCELLED; NOT_COUNTED_AS_PASS
PR11_RUNTIME_EVIDENCE=TARGET_EXACT_DATAPACK_DISPLAY_ENTITY_GAMETEST_PASS; REAL_ANIMATED_JAVA_PLUGIN_EXPORT_UNPROVEN; CLIENT_RESOURCE_PACK_RENDER_UNPROVEN; FULL_MODPACK_RUNTIME_UNPROVEN; runtimeEvidence=UNPROVEN; runtimeValidated=false; f4I6Evidence=false
PR11_PROVIDER_BOUNDARY=ANIMATED_JAVA_DISPLAY_ENTITY_AUTHORING_EXPORT_PROFILE; NO_PHYSICAL_RUNTIME_MOD_INVENTED; NO_SERVER_AUTHORITATIVE_ENTITY_SUBSTITUTION; NO_GECKOLIB_AZURELIB_EMF_CONVERSION
PR11_STATE=MERGED_POSTMERGE_ACTIONS_GREEN_PREMERGE_SONAR_GREEN_TARGET_EXACT_DATAPACK_DISPLAY_ENTITY_GAMETEST_PASS_REAL_PLUGIN_EXPORT_UNPROVEN; GLOBAL_MAIN_SONAR_NOT_PASS"""
replace_once(anchor, anchor + "\n" + pr11)

replace_once(
    "ART_FRONTIER=M4_M5_M6_M8_M3_I1_BASELINE_GREEN; PR5_GENERIC_ANIMATION_MERGED; PR6_GECKOLIB_ADAPTER_MERGED_REFERENCE_ONLY_RUNTIME_UNPROVEN; PR7_AZURELIB_ADAPTER_MERGED_ACTIONS_GREEN_SONAR_NOT_GREEN_REFERENCE_ONLY_RUNTIME_UNPROVEN; PR8_NEOFORGE_NATIVE_ANIMATION_MERGED_TARGET_EXACT_CODEC_COMPILE_PASS_LIVE_RUNTIME_UNPROVEN; PR9_EASY_MODEL_ENTITIES_MERGED_TARGET_EXACT_SOURCE_GAMETEST_PASS_PHYSICAL_JAR_FULL_MODPACK_RUNTIME_UNPROVEN; PR10_EMF_CEM_MERGED_UPSTREAM_SOURCE_BUILD_PASS_TARGET_EXACT_RUNTIME_UNPROVEN; NEXT=PR11_ANIMATED_JAVA_AUDIT",
    "ART_FRONTIER=M4_M5_M6_M8_M3_I1_BASELINE_GREEN; PR5_GENERIC_ANIMATION_MERGED; PR6_GECKOLIB_ADAPTER_MERGED_REFERENCE_ONLY_RUNTIME_UNPROVEN; PR7_AZURELIB_ADAPTER_MERGED_ACTIONS_GREEN_SONAR_NOT_GREEN_REFERENCE_ONLY_RUNTIME_UNPROVEN; PR8_NEOFORGE_NATIVE_ANIMATION_MERGED_TARGET_EXACT_CODEC_COMPILE_PASS_LIVE_RUNTIME_UNPROVEN; PR9_EASY_MODEL_ENTITIES_MERGED_TARGET_EXACT_SOURCE_GAMETEST_PASS_PHYSICAL_JAR_FULL_MODPACK_RUNTIME_UNPROVEN; PR10_EMF_CEM_MERGED_UPSTREAM_SOURCE_BUILD_PASS_TARGET_EXACT_RUNTIME_UNPROVEN; PR11_ANIMATED_JAVA_MERGED_TARGET_EXACT_DATAPACK_DISPLAY_ENTITY_GAMETEST_PASS_REAL_PLUGIN_EXPORT_UNPROVEN; NEXT=PR12_PLAYER_PROFILES_AUDIT",
)
replace_once(
    "FACTORY_GLOBAL_SONAR_AT_CURRENT_MAIN=ANALYSIS_FAILED; CHECK=103377105982; CONCLUSION=CANCELLED; DO_NOT_LABEL_FACTORY_GLOBALLY_GREEN",
    "FACTORY_GLOBAL_SONAR_AT_CURRENT_MAIN=ANALYSIS_FAILED; CHECK=103413605981; CONCLUSION=CANCELLED; DO_NOT_LABEL_FACTORY_GLOBALLY_GREEN",
)
replace_once(
    "FACTORY_GLOBAL_SONAR_BLOCKER=MAIN_BRANCH_ANALYSIS_FAILED_ON_PR10_MERGE_COMMIT; PREMERGE_PR10_QUALITY_GATE_PASS_DOES_NOT_CLEAR_GLOBAL_MAIN_SONAR_STATE",
    "FACTORY_GLOBAL_SONAR_BLOCKER=MAIN_BRANCH_ANALYSIS_FAILED_ON_PR11_MERGE_COMMIT; PREMERGE_PR11_QUALITY_GATE_PASS_DOES_NOT_CLEAR_GLOBAL_MAIN_SONAR_STATE",
)
replace_once(
    "USER_STOP_BOUNDARY=HISTORICAL_BOUNDARY_CLEARED_BY_USER_PROSSIGA; PR10_EXECUTION_COMPLETED_AFTER_BOUNDARY",
    "USER_STOP_BOUNDARY=HISTORICAL_BOUNDARY_CLEARED_BY_USER_PROSSIGA; PR11_EXECUTION_COMPLETED_AFTER_BOUNDARY",
)
next_lines = [line for line in text.splitlines() if line.startswith("NEXT_ACTION=")]
if len(next_lines) != 1:
    raise SystemExit(f"Expected exactly one NEXT_ACTION line, found {len(next_lines)}")
current_next = next_lines[0]
required_next_fragments = [
    "BEGIN_PR11_ANIMATED_JAVA_AUDIT",
    "DISPLAY_ENTITY_DATAPACK_RESOURCEPACK_PROFILE",
    "DO_NOT_CLAIM_REAL_HANDOFF",
    "F4/I6_REMAINS_NOT_COMPLETE",
    "I7_REMAINS_BLOCKED",
]
missing = [fragment for fragment in required_next_fragments if fragment not in current_next]
if missing:
    raise SystemExit(f"NEXT_ACTION authority drift: missing {missing}")
replace_once(
    current_next,
    "NEXT_ACTION=BEGIN_PR12_PLAYER_PROFILES_AUDIT; FIRST_RECHECK_PHYSICAL_MODLIST_CURRENT_REPO_BRANCHES_PRS_STATUS_AND_EXACT_CPM_PAL_PLAYER_ANIMATOR_CONTRACTS; CPM_EXPERIMENTAL; PAL_HANDOFF; PLAYER_ANIMATOR_AUDIT; PRESERVE_SOURCE_FORMATS; NO_SILENT_PROVIDER_CONVERSION; DO_NOT_CLAIM_REAL_HANDOFF; F4/I6_REMAINS_NOT_COMPLETE; I7_REMAINS_BLOCKED",
)

if text.count("I6_REAL_HANDOFF=NOT_COMPLETE") != 1:
    raise SystemExit("I6_REAL_HANDOFF invariant missing or duplicated")
if text.count("I7_STATE=BLOCKED_BY_F4_REAL_I6_HANDOFF") != 1:
    raise SystemExit("I7_STATE invariant missing or duplicated")

path.write_text(text)
