from pathlib import Path

status_path = Path("STATUS.md")
text = status_path.read_text(encoding="utf-8")
lines = text.splitlines()


def replace_prefix(prefix: str, replacement: str) -> None:
    matches = [i for i, line in enumerate(lines) if line.startswith(prefix)]
    if len(matches) != 1:
        raise SystemExit(f"Expected exactly one {prefix!r} line, found {len(matches)}")
    lines[matches[0]] = replacement


def find_prefix(prefix: str) -> int:
    matches = [i for i, line in enumerate(lines) if line.startswith(prefix)]
    if len(matches) != 1:
        raise SystemExit(f"Expected exactly one {prefix!r} line, found {len(matches)}")
    return matches[0]

if any(line.startswith("PR12_") for line in lines):
    raise SystemExit("PR12 block already present; refusing duplicate materialization")

replace_prefix(
    "FACTORY_PHASE=",
    "FACTORY_PHASE=ART_PR12_PLAYER_PROFILES_MERGED_POSTMERGE_ACTIONS_GREEN_PREMERGE_SONAR_GREEN_PROVIDER_RUNTIME_UNPROVEN_MAIN_SONAR_ANALYSIS_CANCELLED_STATUS_CLOSEOUT",
)
replace_prefix("CURRENT_BRANCH=", "CURRENT_BRANCH=docs/art-pr12-closeout-status")
replace_prefix(
    "CURRENT_MAIN_BEFORE_STATUS_UPDATE=",
    "CURRENT_MAIN_BEFORE_STATUS_UPDATE=d3deb0497c0f9f1577824d9b737157b450b16e38",
)
replace_prefix(
    "HEAD_AT_LAST_GREEN_VERIFICATION=",
    "HEAD_AT_LAST_GREEN_VERIFICATION=d3deb0497c0f9f1577824d9b737157b450b16e38",
)
replace_prefix(
    "OPEN_PRS_AT_STATUS_WRITE=",
    "OPEN_PRS_AT_STATUS_WRITE=PR63_MERGED; PR12_STATUS_CLOSEOUT_PR_PENDING; NO_OTHER_OPEN_PRS",
)

pr11_state_idx = find_prefix("PR11_STATE=")
pr12_block = [
    "PR12_PLAN_TARGET=PLAYER_PROFILES; TARGET=MINECRAFT_1.21.1_NEOFORGE_21.1.248_JAVA_21",
    "PR12_PLAYER_PROFILES_PR=63",
    "PR12_PLAYER_PROFILES_FINAL_HEAD=84d9263540037941ab3f1d3ac179038b640fffc2",
    "PR12_PLAYER_PROFILES_MERGE_COMMIT=d3deb0497c0f9f1577824d9b737157b450b16e38",
    "PR12_PHYSICAL_PROVIDER_VERSIONS=CPM_0.6.27a; PLAYER_ANIMATION_LIBRARY_1.1.6+mc.1.21.1; PLAYER_ANIMATOR_2.0.4+1.21.1",
    "PR12_CPM_POLICY=CPMPROJECT_SOURCE_PRESERVED; CPM_PLUGIN; HUMAN_ONLY; MCP_NEVER; AUTOMATED_LOSSLESS_ROUNDTRIP_NOT_CLAIMED",
    "PR12_PAL_POLICY=SEPARATE_RUNTIME_CONSUMER_HANDOFF_PROFILE; RESOURCE_PATH=assets/<namespace>/player_animations/; SOURCE_PRESERVING_HANDOFF",
    "PR12_PLAYER_ANIMATOR_AUTHORITY=KosmX/minecraftPlayerAnimator@cb3227efc19ec46065597332ae265076d0f2b495; VERSION=2.0.4+1.21.1",
    "PR12_PLAYER_ANIMATOR_SIDE_BOUNDARY=RUNTIME_SIDE=BOTH; RESOURCE_REGISTRY_SIDE=CLIENT; PROVIDER_CLIENT_ONLY=UNDEFINED",
    "PR12_CROSS_PROVIDER_POLICY=NO_AUTOMATIC_PAL_PLAYER_ANIMATOR_CONVERSION; NO_SILENT_PROVIDER_CONVERSION",
    "PR12_FINAL_PR_RUN=34651545770; SUCCESS; CONTRACT=8_OF_8_PASS; REGRESSIONS=52_OF_52_PASS; BUNDLE=PASS; WHITESPACE=PASS",
    "PR12_PREMERGE_SONAR=CHECK_103435012961; QUALITY_GATE_PASS; 0_NEW_ISSUES; 0_ACCEPTED_ISSUES; 0_SECURITY_HOTSPOTS; 0.0_PERCENT_DUPLICATION_ON_NEW_CODE",
    "PR12_POSTMERGE_ACTIONS=26_OF_26_WORKFLOWS_SUCCESS; MERGE_COMMIT=d3deb0497c0f9f1577824d9b737157b450b16e38",
    "PR12_POSTMERGE_SONAR=CHECK_103437143765; ANALYSIS_FAILED; CONCLUSION_CANCELLED; NOT_COUNTED_AS_PASS",
    "PR12_RUNTIME_EVIDENCE=CONTRACT_AND_HANDOFF_PASS; PROVIDER_REAL_RUNTIME_UNPROVEN; LIVE_CLIENT_UNPROVEN; FULL_MODPACK_RUNTIME_UNPROVEN; runtimeEvidence=UNPROVEN; runtimeValidated=false; f4I6Evidence=false",
    "PR12_STATE=MERGED_POSTMERGE_ACTIONS_GREEN_PREMERGE_SONAR_GREEN_PROVIDER_RUNTIME_UNPROVEN; GLOBAL_MAIN_SONAR_NOT_PASS",
]
lines[pr11_state_idx + 1:pr11_state_idx + 1] = pr12_block

art_idx = find_prefix("ART_FRONTIER=")
old_art = lines[art_idx]
old_suffix = "; NEXT=PR12_PLAYER_PROFILES_AUDIT"
if old_suffix not in old_art:
    raise SystemExit("ART_FRONTIER does not contain expected PR12 frontier")
lines[art_idx] = old_art.replace(
    old_suffix,
    "; PR12_PLAYER_PROFILES_MERGED_CONTRACT_HANDOFF_PASS_PROVIDER_RUNTIME_UNPROVEN; NEXT=PR13_EXTERNAL_DCC_BLENDER_EPIC_FIGHT_AUDIT",
    1,
)

replace_prefix(
    "FACTORY_GLOBAL_SONAR_AT_CURRENT_MAIN=",
    "FACTORY_GLOBAL_SONAR_AT_CURRENT_MAIN=ANALYSIS_FAILED; CHECK=103437143765; CONCLUSION=CANCELLED; DO_NOT_LABEL_FACTORY_GLOBALLY_GREEN",
)
replace_prefix(
    "FACTORY_GLOBAL_SONAR_BLOCKER=",
    "FACTORY_GLOBAL_SONAR_BLOCKER=MAIN_BRANCH_ANALYSIS_FAILED_ON_PR12_MERGE; CHECK=103437143765; PREMERGE_PR12_QUALITY_GATE_PASS_DOES_NOT_CLEAR_GLOBAL_MAIN_SONAR_STATE",
)
replace_prefix(
    "USER_STOP_BOUNDARY=",
    "USER_STOP_BOUNDARY=HISTORICAL_BOUNDARY_CLEARED_BY_USER_PROSSIGA; PR12_EXECUTION_COMPLETED_AFTER_BOUNDARY",
)
replace_prefix(
    "NEXT_ACTION=",
    "NEXT_ACTION=BEGIN_PR13_EXTERNAL_DCC_BLENDER_EPIC_FIGHT_AUDIT; FIRST_RECHECK_PHYSICAL_MODLIST_CURRENT_REPO_BRANCHES_PRS_STATUS_AND_EXACT_BLENDER_EPIC_FIGHT_SOURCE_OUTPUT_CONTRACTS; BLENDER_AUTHORITATIVE_CUSTOM_COMBAT_ANIMATION; NO_FALSE_DIRECT_BLOCKBENCH_TO_EPIC_FIGHT_EXPORT; PRESERVE_NATIVE_AUTHORING_SOURCE; NO_SILENT_PROVIDER_CONVERSION; DO_NOT_CLAIM_REAL_HANDOFF; F4/I6_REMAINS_NOT_COMPLETE; I7_REMAINS_BLOCKED",
)

if lines[find_prefix("I6_REAL_HANDOFF=")] != "I6_REAL_HANDOFF=NOT_COMPLETE":
    raise SystemExit("I6 invariant changed unexpectedly")
if lines[find_prefix("I7_STATE=")] != "I7_STATE=BLOCKED_BY_F4_REAL_I6_HANDOFF":
    raise SystemExit("I7 invariant changed unexpectedly")
if sum(1 for line in lines if line.startswith("PR12_STATE=")) != 1:
    raise SystemExit("PR12 block did not materialize exactly once")
if "NEXT=PR13_EXTERNAL_DCC_BLENDER_EPIC_FIGHT_AUDIT" not in lines[find_prefix("ART_FRONTIER=")]:
    raise SystemExit("PR13 frontier did not materialize")

status_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
