from pathlib import Path

path = Path("STATUS.md")
text = path.read_text()


def replace_once(old: str, new: str) -> None:
    global text
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"Expected exactly one occurrence, found {count}: {old}")
    text = text.replace(old, new, 1)


replace_once(
    "CURRENT_MAIN_BEFORE_STATUS_UPDATE=a4d9a715f8e9213d458df625336c1ef8a096fbf9",
    "CURRENT_MAIN_BEFORE_STATUS_UPDATE=aa4904d186f482a80358df56a3b426be24bfa215",
)
replace_once(
    "HEAD_AT_LAST_GREEN_VERIFICATION=a4d9a715f8e9213d458df625336c1ef8a096fbf9",
    "HEAD_AT_LAST_GREEN_VERIFICATION=aa4904d186f482a80358df56a3b426be24bfa215",
)
replace_once(
    "OPEN_PRS_AT_STATUS_WRITE=PR59_MERGED; PR60_CONSTRUCTION_C7_OPEN_NON_OVERLAPPING; PR11_STATUS_CLOSEOUT_PR_PENDING",
    "OPEN_PRS_AT_STATUS_WRITE=PR59_MERGED; PR60_CONSTRUCTION_C7_MERGED_NON_OVERLAPPING; PR11_STATUS_CLOSEOUT_PR_PENDING; NO_OTHER_OPEN_PRS",
)
replace_once(
    "FACTORY_GLOBAL_SONAR_AT_CURRENT_MAIN=ANALYSIS_FAILED; CHECK=103413605981; CONCLUSION=CANCELLED; DO_NOT_LABEL_FACTORY_GLOBALLY_GREEN",
    "FACTORY_GLOBAL_SONAR_AT_CURRENT_MAIN=ANALYSIS_FAILED; CHECK=103416946036; CONCLUSION=CANCELLED; DO_NOT_LABEL_FACTORY_GLOBALLY_GREEN",
)
replace_once(
    "FACTORY_GLOBAL_SONAR_BLOCKER=MAIN_BRANCH_ANALYSIS_FAILED_ON_PR11_MERGE_COMMIT; PREMERGE_PR11_QUALITY_GATE_PASS_DOES_NOT_CLEAR_GLOBAL_MAIN_SONAR_STATE",
    "FACTORY_GLOBAL_SONAR_BLOCKER=MAIN_BRANCH_ANALYSIS_FAILED_ON_CURRENT_MAIN_AFTER_PR60; CHECK=103416946036; PREMERGE_PR11_QUALITY_GATE_PASS_DOES_NOT_CLEAR_GLOBAL_MAIN_SONAR_STATE",
)

if text.count("I6_REAL_HANDOFF=NOT_COMPLETE") != 1:
    raise SystemExit("I6_REAL_HANDOFF invariant missing or duplicated")
if text.count("I7_STATE=BLOCKED_BY_F4_REAL_I6_HANDOFF") != 1:
    raise SystemExit("I7_STATE invariant missing or duplicated")
if text.count("NEXT=PR12_PLAYER_PROFILES_AUDIT") != 1:
    raise SystemExit("PR12 frontier missing or duplicated")

path.write_text(text)
